source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:stanwood/Cocoa_Pods_Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'STWSocialKit_Example' do
    pod 'StanwoodSocial', :path => '../'
    #pod 'OAuthSwift'
    pod 'Locksmith'
    pod 'YouTubePlayer', :git => 'https://github.com/talezion/Swift-YouTube-Player', :commit => 'c18c39fad86e1cfb35380acd12b58fdaa57cdfe9'
    pod 'FontAwesome.swift', '~> 1.3.0'
    pod 'Kingfisher', '~> 3.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['FontAwesome.swift'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
