
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/stanwood/Cocoa_Pods_Specs.git'

use_frameworks!

target 'STWSocialKit_Example' do
    pod 'STWSocialKit'
    pod 'OAuthSwift'
    pod 'Locksmith'
    pod 'YouTubePlayer', :git => 'https://github.com/talezion/Swift-YouTube-Player', :commit => 'c18c39fad86e1cfb35380acd12b58fdaa57cdfe9'
    pod 'FontAwesome.swift'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0.1'
        end
    end
end
